apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: demo
        image: marcosalarcon/appfrontend:v1
        ports:
        - containerPort: 80