apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: demo
        image: 76591745/spring
        ports:
        - containerPort: 8080